# This is a basic workflow to generate build
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'main'

  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v4
        with:
          app_dir: "TA-sysmon-deploy-for-cyences"
          to_make_permission_changes: true
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_utilities: "whats_in_the_app"
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}
